### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by vjpsyverson** [paleobiodb/pbdb-main#33]
Updates to resource table. Please file more here and I will do them all at once.

- [x] update title of "paleobiologyDatabase.R" to "velociraptr"

- [x] add issue-reporting links

- [x] fix whatever's making the "Educational Resources" category go crazy (one is duplicated, the other is showing up in Tutorials)

- [x] add https://github.com/paleobiodb/teachPaleobiology to "Educational Resources"

**Comment by aazaff** [comment]
Per our previous meeting, the velociraptr package is now stored a subdirectory of the pbdb_utilities repository where I assume other resources will be placed.

**Comment by cambro** [comment]
https://github.com/paleobiodb/teachPaleobiology
This really does need to be added to: https://paleobiodb.org/#/resources
Can we get this dropped in @vjpsyverson ?

**Comment by vjpsyverson** [comment]
Definitely, but how do you want it in there? The pbdb-utilities repo is already linked. Do you want it as a separate entry?

------

**Comment by aazaff** [comment]
https://github.com/paleobiodb/teachPaleobiology is its own repo and separate from the utilities repo.

**Comment by cambro** [comment]
Yes, it should be there. It is a course curriculum.
