### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/pbdb-main#34]
All hyper-links to external resources to should spawn new browser pages (or tabs). This is accomplished with the target="_blank" attribute in an anchor tag. The rational is that a user should not have to repeatedly press the browsers 'back' button to find the main navigation menu (whether it be the external menu bar (used on the landing page and navigator) or the one provided by the framework supporting the actual PBDB web application.

**Comment by jpjenk** [comment]
Looks like it is just links that take the user to GitHub, but there are several of those.

**Comment by markuhen** [comment]
The Github ones seem to behave correctly; the Youtube ones don't, though.
