### ISSUE TITLE
Problems with /#/

### ISSUE THREAD

**Issue by jczaplew** [paleobiodb/pbdb-main#41]
**Migrated from https://github.com/paleobiodb/navigator/issues/40**

Resources external to the PBDB web application (ie. assets managed in pbdb-main) insert a # before most page links such as #/resources.

This functions as both a jump-to anchor in the resulting page but also triggers the appropriate JavaScript code to generate the page in the first place thus it can not be omitted.

Online forms which allow the attachment of URLs to show examples of work have been found to reject the URL because of this symbol. In particular, NSF does not allow it!

Request the # symbol as the root of the JS code be changed to something else.

**Comment by jczaplew** [comment]
Simply removing the hash from the URLs would break all existing links that may be out in the wild, so this requires a few changes.

1. Modify the website so that routing is either a) handled without hashes, or b) handled server side. If option A is chosen, the nginx config will need to be updated so that selected routes are routed to the index page of the splash (see https://github.com/UW-Macrostrat/nginx-config/blob/cci/sites-enabled/rockd.conf#L33 for an example of what I mean). 

2. Modify the nginx config so that all links that currently exist are redirected with a 301 to the new URI.

**Comment by cambro** [comment]
This issue is not a PBDB issue. This is a "others are incorrect" issue. The use of '#' in URLs is valid. The fact that some sites/places don't seem to recognize this is not a PBDB problem. We shouldn't make issues for ourselves that amount to accounting for failures by others to recognize valid URLs.
