### ISSUE TITLE
publication submission form not displaying existing pubs

### ISSUE THREAD

**Issue by cambro** [paleobiodb/pbdb-main#6]
404 thrown for forms/assets/js/lib/d3.min.js

**Comment by vjpsyverson** [comment]
Which submission form is this, exactly? The publications paper list doesn't have a submission form, just a mailto:link to sec@paleobiodb, and the list itself seems to be up-to-date. Can I close this issue?

**Comment by cambro** [comment]
Publication form also doesn't appear to work at all, unless publication form password has been changed and I do not know.

**Comment by cambro** [comment]
Answer to "which form question"... 
https://github.com/paleobiodb/pbdb-main/blob/master/forms/publication_submission.html

**Comment by markuhen** [comment]
@vjpsyverson: once @jpjenk finishes the new Wing page, you will redirect the "Official Publications" link in the splash page to it and delete the existing page.

**Comment by vjpsyverson** [comment]
Fixed by @jpjenk with #42
